use ratatui::style::Color;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ThemeMode {
    Light,
    Dark,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ThemePreset {
    // Original 8
    NyzhiDark,
    NyzhiLight,
    TokyoNight,
    CatppuccinMocha,
    Dracula,
    SolarizedDark,
    SolarizedLight,
    GruvboxDark,
    // New 52
    CatppuccinLatte,
    CatppuccinFrappe,
    CatppuccinMacchiato,
    Nord,
    NordLight,
    RosePine,
    RosePineMoon,
    RosePineDawn,
    Kanagawa,
    KanagawaLight,
    EverforestDark,
    EverforestLight,
    AyuDark,
    AyuLight,
    AyuMirage,
    OneDark,
    OneLight,
    NightOwl,
    NightOwlLight,
    MaterialDarker,
    MaterialOcean,
    MaterialPalenight,
    GitHubDark,
    GitHubLight,
    GitHubDimmed,
    Nightfox,
    Dawnfox,
    Carbonfox,
    MonokaiPro,
    MonokaiClassic,
    Sonokai,
    Moonfly,
    Nightfly,
    NoctisAzureus,
    NoctisLux,
    Zenbones,
    Zenwritten,
    MinDark,
    MinLight,
    Panda,
    Synthwave84,
    Cobalt2,
    Andromeda,
    ShadesOfPurple,
    Iceberg,
    GruvboxLight,
    Srcery,
    WinterDark,
    WinterLight,
    Tender,
    Vesper,
    Apprentice,
}

impl ThemePreset {
    pub const ALL: &[ThemePreset] = &[
        ThemePreset::NyzhiDark,
        ThemePreset::NyzhiLight,
        ThemePreset::TokyoNight,
        ThemePreset::CatppuccinMocha,
        ThemePreset::Dracula,
        ThemePreset::SolarizedDark,
        ThemePreset::SolarizedLight,
        ThemePreset::GruvboxDark,
        ThemePreset::CatppuccinLatte,
        ThemePreset::CatppuccinFrappe,
        ThemePreset::CatppuccinMacchiato,
        ThemePreset::Nord,
        ThemePreset::NordLight,
        ThemePreset::RosePine,
        ThemePreset::RosePineMoon,
        ThemePreset::RosePineDawn,
        ThemePreset::Kanagawa,
        ThemePreset::KanagawaLight,
        ThemePreset::EverforestDark,
        ThemePreset::EverforestLight,
        ThemePreset::AyuDark,
        ThemePreset::AyuLight,
        ThemePreset::AyuMirage,
        ThemePreset::OneDark,
        ThemePreset::OneLight,
        ThemePreset::NightOwl,
        ThemePreset::NightOwlLight,
        ThemePreset::MaterialDarker,
        ThemePreset::MaterialOcean,
        ThemePreset::MaterialPalenight,
        ThemePreset::GitHubDark,
        ThemePreset::GitHubLight,
        ThemePreset::GitHubDimmed,
        ThemePreset::Nightfox,
        ThemePreset::Dawnfox,
        ThemePreset::Carbonfox,
        ThemePreset::MonokaiPro,
        ThemePreset::MonokaiClassic,
        ThemePreset::Sonokai,
        ThemePreset::Moonfly,
        ThemePreset::Nightfly,
        ThemePreset::NoctisAzureus,
        ThemePreset::NoctisLux,
        ThemePreset::Zenbones,
        ThemePreset::Zenwritten,
        ThemePreset::MinDark,
        ThemePreset::MinLight,
        ThemePreset::Panda,
        ThemePreset::Synthwave84,
        ThemePreset::Cobalt2,
        ThemePreset::Andromeda,
        ThemePreset::ShadesOfPurple,
        ThemePreset::Iceberg,
        ThemePreset::GruvboxLight,
        ThemePreset::Srcery,
        ThemePreset::WinterDark,
        ThemePreset::WinterLight,
        ThemePreset::Tender,
        ThemePreset::Vesper,
        ThemePreset::Apprentice,
    ];

    pub fn name(self) -> &'static str {
        match self {
            ThemePreset::NyzhiDark => "nyzhi-dark",
            ThemePreset::NyzhiLight => "nyzhi-light",
            ThemePreset::TokyoNight => "tokyonight",
            ThemePreset::CatppuccinMocha => "catppuccin-mocha",
            ThemePreset::Dracula => "dracula",
            ThemePreset::SolarizedDark => "solarized-dark",
            ThemePreset::SolarizedLight => "solarized-light",
            ThemePreset::GruvboxDark => "gruvbox-dark",
            ThemePreset::CatppuccinLatte => "catppuccin-latte",
            ThemePreset::CatppuccinFrappe => "catppuccin-frappe",
            ThemePreset::CatppuccinMacchiato => "catppuccin-macchiato",
            ThemePreset::Nord => "nord",
            ThemePreset::NordLight => "nord-light",
            ThemePreset::RosePine => "rose-pine",
            ThemePreset::RosePineMoon => "rose-pine-moon",
            ThemePreset::RosePineDawn => "rose-pine-dawn",
            ThemePreset::Kanagawa => "kanagawa",
            ThemePreset::KanagawaLight => "kanagawa-light",
            ThemePreset::EverforestDark => "everforest-dark",
            ThemePreset::EverforestLight => "everforest-light",
            ThemePreset::AyuDark => "ayu-dark",
            ThemePreset::AyuLight => "ayu-light",
            ThemePreset::AyuMirage => "ayu-mirage",
            ThemePreset::OneDark => "one-dark",
            ThemePreset::OneLight => "one-light",
            ThemePreset::NightOwl => "night-owl",
            ThemePreset::NightOwlLight => "night-owl-light",
            ThemePreset::MaterialDarker => "material-darker",
            ThemePreset::MaterialOcean => "material-ocean",
            ThemePreset::MaterialPalenight => "material-palenight",
            ThemePreset::GitHubDark => "github-dark",
            ThemePreset::GitHubLight => "github-light",
            ThemePreset::GitHubDimmed => "github-dimmed",
            ThemePreset::Nightfox => "nightfox",
            ThemePreset::Dawnfox => "dawnfox",
            ThemePreset::Carbonfox => "carbonfox",
            ThemePreset::MonokaiPro => "monokai-pro",
            ThemePreset::MonokaiClassic => "monokai-classic",
            ThemePreset::Sonokai => "sonokai",
            ThemePreset::Moonfly => "moonfly",
            ThemePreset::Nightfly => "nightfly",
            ThemePreset::NoctisAzureus => "noctis-azureus",
            ThemePreset::NoctisLux => "noctis-lux",
            ThemePreset::Zenbones => "zenbones",
            ThemePreset::Zenwritten => "zenwritten",
            ThemePreset::MinDark => "min-dark",
            ThemePreset::MinLight => "min-light",
            ThemePreset::Panda => "panda",
            ThemePreset::Synthwave84 => "synthwave84",
            ThemePreset::Cobalt2 => "cobalt2",
            ThemePreset::Andromeda => "andromeda",
            ThemePreset::ShadesOfPurple => "shades-of-purple",
            ThemePreset::Iceberg => "iceberg",
            ThemePreset::GruvboxLight => "gruvbox-light",
            ThemePreset::Srcery => "srcery",
            ThemePreset::WinterDark => "winter-dark",
            ThemePreset::WinterLight => "winter-light",
            ThemePreset::Tender => "tender",
            ThemePreset::Vesper => "vesper",
            ThemePreset::Apprentice => "apprentice",
        }
    }

    pub fn display_name(self) -> &'static str {
        match self {
            ThemePreset::NyzhiDark => "Nyzhi Dark",
            ThemePreset::NyzhiLight => "Nyzhi Light",
            ThemePreset::TokyoNight => "Tokyo Night",
            ThemePreset::CatppuccinMocha => "Catppuccin Mocha",
            ThemePreset::Dracula => "Dracula",
            ThemePreset::SolarizedDark => "Solarized Dark",
            ThemePreset::SolarizedLight => "Solarized Light",
            ThemePreset::GruvboxDark => "Gruvbox Dark",
            ThemePreset::CatppuccinLatte => "Catppuccin Latte",
            ThemePreset::CatppuccinFrappe => "Catppuccin Frappe",
            ThemePreset::CatppuccinMacchiato => "Catppuccin Macchiato",
            ThemePreset::Nord => "Nord",
            ThemePreset::NordLight => "Nord Light",
            ThemePreset::RosePine => "Rose Pine",
            ThemePreset::RosePineMoon => "Rose Pine Moon",
            ThemePreset::RosePineDawn => "Rose Pine Dawn",
            ThemePreset::Kanagawa => "Kanagawa",
            ThemePreset::KanagawaLight => "Kanagawa Light",
            ThemePreset::EverforestDark => "Everforest Dark",
            ThemePreset::EverforestLight => "Everforest Light",
            ThemePreset::AyuDark => "Ayu Dark",
            ThemePreset::AyuLight => "Ayu Light",
            ThemePreset::AyuMirage => "Ayu Mirage",
            ThemePreset::OneDark => "One Dark",
            ThemePreset::OneLight => "One Light",
            ThemePreset::NightOwl => "Night Owl",
            ThemePreset::NightOwlLight => "Night Owl Light",
            ThemePreset::MaterialDarker => "Material Darker",
            ThemePreset::MaterialOcean => "Material Ocean",
            ThemePreset::MaterialPalenight => "Material Palenight",
            ThemePreset::GitHubDark => "GitHub Dark",
            ThemePreset::GitHubLight => "GitHub Light",
            ThemePreset::GitHubDimmed => "GitHub Dimmed",
            ThemePreset::Nightfox => "Nightfox",
            ThemePreset::Dawnfox => "Dawnfox",
            ThemePreset::Carbonfox => "Carbonfox",
            ThemePreset::MonokaiPro => "Monokai Pro",
            ThemePreset::MonokaiClassic => "Monokai Classic",
            ThemePreset::Sonokai => "Sonokai",
            ThemePreset::Moonfly => "Moonfly",
            ThemePreset::Nightfly => "Nightfly",
            ThemePreset::NoctisAzureus => "Noctis Azureus",
            ThemePreset::NoctisLux => "Noctis Lux",
            ThemePreset::Zenbones => "Zenbones",
            ThemePreset::Zenwritten => "Zenwritten",
            ThemePreset::MinDark => "Min Dark",
            ThemePreset::MinLight => "Min Light",
            ThemePreset::Panda => "Panda",
            ThemePreset::Synthwave84 => "Synthwave84",
            ThemePreset::Cobalt2 => "Cobalt2",
            ThemePreset::Andromeda => "Andromeda",
            ThemePreset::ShadesOfPurple => "Shades of Purple",
            ThemePreset::Iceberg => "Iceberg",
            ThemePreset::GruvboxLight => "Gruvbox Light",
            ThemePreset::Srcery => "Srcery",
            ThemePreset::WinterDark => "Winter Dark",
            ThemePreset::WinterLight => "Winter Light",
            ThemePreset::Tender => "Tender",
            ThemePreset::Vesper => "Vesper",
            ThemePreset::Apprentice => "Apprentice",
        }
    }

    pub fn from_name(name: &str) -> Self {
        let s = name.to_lowercase().replace(' ', "-").replace('_', "-");
        match s.as_str() {
            "dark" | "nyzhi-dark" | "nyzhidark" => ThemePreset::NyzhiDark,
            "light" | "nyzhi-light" | "nyzhi_light" | "nyzhilight" => ThemePreset::NyzhiLight,
            "tokyonight" | "tokyo-night" | "tokyo_night" => ThemePreset::TokyoNight,
            "catppuccin-mocha" | "catppuccin_mocha" | "catppuccinmocha" | "catppuccin" => {
                ThemePreset::CatppuccinMocha
            }
            "dracula" => ThemePreset::Dracula,
            "solarized-dark" | "solarized_dark" | "solarizeddark" => ThemePreset::SolarizedDark,
            "solarized-light" | "solarized_light" | "solarizedlight" => ThemePreset::SolarizedLight,
            "gruvbox-dark" | "gruvbox_dark" | "gruvboxdark" | "gruvbox" => ThemePreset::GruvboxDark,
            "catppuccin-latte" | "catppuccin_latte" | "catppuccinlatte" => ThemePreset::CatppuccinLatte,
            "catppuccin-frappe" | "catppuccin_frappe" | "catppuccinfrappe" => ThemePreset::CatppuccinFrappe,
            "catppuccin-macchiato" | "catppuccin_macchiato" | "catppuccinmacchiato" => ThemePreset::CatppuccinMacchiato,
            "nord" => ThemePreset::Nord,
            "nord-light" | "nord_light" | "nordlight" => ThemePreset::NordLight,
            "rose-pine" | "rose_pine" | "rosepine" => ThemePreset::RosePine,
            "rose-pine-moon" | "rose_pine_moon" | "rosepinemoon" => ThemePreset::RosePineMoon,
            "rose-pine-dawn" | "rose_pine_dawn" | "rosepinedawn" => ThemePreset::RosePineDawn,
            "kanagawa" => ThemePreset::Kanagawa,
            "kanagawa-light" | "kanagawa_light" | "kanagawalight" => ThemePreset::KanagawaLight,
            "everforest-dark" | "everforest_dark" | "everforestdark" => ThemePreset::EverforestDark,
            "everforest-light" | "everforest_light" | "everforestlight" => ThemePreset::EverforestLight,
            "ayu-dark" | "ayu_dark" | "ayudark" => ThemePreset::AyuDark,
            "ayu-light" | "ayu_light" | "ayulight" => ThemePreset::AyuLight,
            "ayu-mirage" | "ayu_mirage" | "ayumirage" => ThemePreset::AyuMirage,
            "one-dark" | "one_dark" | "onedark" => ThemePreset::OneDark,
            "one-light" | "one_light" | "onelight" => ThemePreset::OneLight,
            "night-owl" | "night_owl" | "nightowl" => ThemePreset::NightOwl,
            "night-owl-light" | "night_owl_light" | "nightowllight" => ThemePreset::NightOwlLight,
            "material-darker" | "material_darker" | "materialdarker" => ThemePreset::MaterialDarker,
            "material-ocean" | "material_ocean" | "materialocean" => ThemePreset::MaterialOcean,
            "material-palenight" | "material_palenight" | "materialpalenight" => ThemePreset::MaterialPalenight,
            "github-dark" | "github_dark" | "githubdark" => ThemePreset::GitHubDark,
            "github-light" | "github_light" | "githublight" => ThemePreset::GitHubLight,
            "github-dimmed" | "github_dimmed" | "githubdimmed" => ThemePreset::GitHubDimmed,
            "nightfox" | "night-fox" | "night_fox" => ThemePreset::Nightfox,
            "dawnfox" | "dawn-fox" | "dawn_fox" => ThemePreset::Dawnfox,
            "carbonfox" | "carbon-fox" | "carbon_fox" => ThemePreset::Carbonfox,
            "monokai-pro" | "monokai_pro" | "monokaipro" => ThemePreset::MonokaiPro,
            "monokai-classic" | "monokai_classic" | "monokaiclassic" => ThemePreset::MonokaiClassic,
            "sonokai" => ThemePreset::Sonokai,
            "moonfly" | "moon-fly" | "moon_fly" => ThemePreset::Moonfly,
            "nightfly" | "night-fly" | "night_fly" => ThemePreset::Nightfly,
            "noctis-azureus" | "noctis_azureus" | "noctisazureus" => ThemePreset::NoctisAzureus,
            "noctis-lux" | "noctis_lux" | "noctislux" => ThemePreset::NoctisLux,
            "zenbones" | "zen-bones" | "zen_bones" => ThemePreset::Zenbones,
            "zenwritten" | "zen-written" | "zen_written" => ThemePreset::Zenwritten,
            "min-dark" | "min_dark" | "mindark" => ThemePreset::MinDark,
            "min-light" | "min_light" | "minlight" => ThemePreset::MinLight,
            "panda" => ThemePreset::Panda,
            "synthwave84" | "synthwave-84" | "synthwave_84" => ThemePreset::Synthwave84,
            "cobalt2" | "cobalt-2" | "cobalt_2" => ThemePreset::Cobalt2,
            "andromeda" => ThemePreset::Andromeda,
            "shades-of-purple" | "shades_of_purple" | "shadesofpurple" => ThemePreset::ShadesOfPurple,
            "iceberg" => ThemePreset::Iceberg,
            "gruvbox-light" | "gruvbox_light" | "gruvboxlight" => ThemePreset::GruvboxLight,
            "srcery" => ThemePreset::Srcery,
            "winter-dark" | "winter_dark" | "winterdark" => ThemePreset::WinterDark,
            "winter-light" | "winter_light" | "winterlight" => ThemePreset::WinterLight,
            "tender" => ThemePreset::Tender,
            "vesper" => ThemePreset::Vesper,
            "apprentice" => ThemePreset::Apprentice,
            _ => ThemePreset::NyzhiDark,
        }
    }

    pub fn mode(self) -> ThemeMode {
        match self {
            ThemePreset::NyzhiLight
            | ThemePreset::SolarizedLight
            | ThemePreset::CatppuccinLatte
            | ThemePreset::NordLight
            | ThemePreset::RosePineDawn
            | ThemePreset::KanagawaLight
            | ThemePreset::EverforestLight
            | ThemePreset::AyuLight
            | ThemePreset::OneLight
            | ThemePreset::NightOwlLight
            | ThemePreset::GitHubLight
            | ThemePreset::Dawnfox
            | ThemePreset::NoctisLux
            | ThemePreset::MinLight
            | ThemePreset::GruvboxLight
            | ThemePreset::WinterLight => ThemeMode::Light,
            _ => ThemeMode::Dark,
        }
    }

    pub fn bg_page_color(self) -> Color {
        match self {
            ThemePreset::NyzhiDark => Color::Rgb(0, 0, 0),
            ThemePreset::NyzhiLight => Color::Rgb(245, 240, 232),
            ThemePreset::TokyoNight => Color::Rgb(26, 27, 38),
            ThemePreset::CatppuccinMocha => Color::Rgb(30, 30, 46),
            ThemePreset::Dracula => Color::Rgb(40, 42, 54),
            ThemePreset::SolarizedDark => Color::Rgb(0, 43, 54),
            ThemePreset::SolarizedLight => Color::Rgb(253, 246, 227),
            ThemePreset::GruvboxDark => Color::Rgb(40, 40, 40),
            ThemePreset::CatppuccinLatte => Color::Rgb(239, 241, 245),
            ThemePreset::CatppuccinFrappe => Color::Rgb(48, 52, 70),
            ThemePreset::CatppuccinMacchiato => Color::Rgb(36, 39, 58),
            ThemePreset::Nord => Color::Rgb(46, 52, 64),
            ThemePreset::NordLight => Color::Rgb(236, 239, 244),
            ThemePreset::RosePine => Color::Rgb(25, 23, 36),
            ThemePreset::RosePineMoon => Color::Rgb(35, 33, 54),
            ThemePreset::RosePineDawn => Color::Rgb(250, 244, 237),
            ThemePreset::Kanagawa => Color::Rgb(31, 31, 40),
            ThemePreset::KanagawaLight => Color::Rgb(243, 243, 243),
            ThemePreset::EverforestDark => Color::Rgb(47, 53, 47),
            ThemePreset::EverforestLight => Color::Rgb(253, 246, 227),
            ThemePreset::AyuDark => Color::Rgb(11, 14, 20),
            ThemePreset::AyuLight => Color::Rgb(250, 250, 250),
            ThemePreset::AyuMirage => Color::Rgb(29, 32, 42),
            ThemePreset::OneDark => Color::Rgb(40, 44, 52),
            ThemePreset::OneLight => Color::Rgb(250, 250, 250),
            ThemePreset::NightOwl => Color::Rgb(1, 22, 39),
            ThemePreset::NightOwlLight => Color::Rgb(251, 251, 251),
            ThemePreset::MaterialDarker => Color::Rgb(33, 33, 33),
            ThemePreset::MaterialOcean => Color::Rgb(15, 17, 26),
            ThemePreset::MaterialPalenight => Color::Rgb(41, 45, 62),
            ThemePreset::GitHubDark => Color::Rgb(13, 17, 23),
            ThemePreset::GitHubLight => Color::Rgb(255, 255, 255),
            ThemePreset::GitHubDimmed => Color::Rgb(34, 39, 46),
            ThemePreset::Nightfox => Color::Rgb(25, 28, 39),
            ThemePreset::Dawnfox => Color::Rgb(250, 244, 237),
            ThemePreset::Carbonfox => Color::Rgb(22, 22, 22),
            ThemePreset::MonokaiPro => Color::Rgb(45, 42, 46),
            ThemePreset::MonokaiClassic => Color::Rgb(39, 40, 34),
            ThemePreset::Sonokai => Color::Rgb(43, 43, 43),
            ThemePreset::Moonfly => Color::Rgb(8, 8, 8),
            ThemePreset::Nightfly => Color::Rgb(1, 13, 32),
            ThemePreset::NoctisAzureus => Color::Rgb(3, 22, 52),
            ThemePreset::NoctisLux => Color::Rgb(254, 246, 225),
            ThemePreset::Zenbones => Color::Rgb(25, 25, 25),
            ThemePreset::Zenwritten => Color::Rgb(245, 240, 232),
            ThemePreset::MinDark => Color::Rgb(20, 20, 20),
            ThemePreset::MinLight => Color::Rgb(255, 255, 255),
            ThemePreset::Panda => Color::Rgb(41, 45, 62),
            ThemePreset::Synthwave84 => Color::Rgb(38, 20, 71),
            ThemePreset::Cobalt2 => Color::Rgb(25, 32, 52),
            ThemePreset::Andromeda => Color::Rgb(35, 36, 44),
            ThemePreset::ShadesOfPurple => Color::Rgb(30, 30, 56),
            ThemePreset::Iceberg => Color::Rgb(22, 26, 34),
            ThemePreset::GruvboxLight => Color::Rgb(251, 241, 199),
            ThemePreset::Srcery => Color::Rgb(28, 27, 25),
            ThemePreset::WinterDark => Color::Rgb(13, 17, 24),
            ThemePreset::WinterLight => Color::Rgb(248, 250, 252),
            ThemePreset::Tender => Color::Rgb(40, 40, 40),
            ThemePreset::Vesper => Color::Rgb(16, 16, 20),
            ThemePreset::Apprentice => Color::Rgb(28, 28, 28),
        }
    }

    pub fn palette(self) -> Theme {
        let mode = self.mode();
        let accent = Accent::NyzhiOrange;
        match self {
            ThemePreset::NyzhiDark => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(0, 0, 0),
                bg_surface: Color::Rgb(0x0A, 0x0A, 0x0C),
                bg_elevated: Color::Rgb(0x1C, 0x1C, 0x22),
                bg_sunken: Color::Rgb(0, 0, 0),
                text_primary: Color::Rgb(0xFA, 0xFA, 0xFA),
                text_secondary: Color::Rgb(0xA1, 0xA1, 0xAA),
                text_tertiary: Color::Rgb(0x71, 0x71, 0x7A),
                text_disabled: Color::Rgb(0x3F, 0x3F, 0x46),
                border_default: Color::Rgb(0x1E, 0x1E, 0x26),
                border_strong: Color::Rgb(0x2C, 0x2C, 0x36),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(0x4A, 0xDE, 0x80),
                danger: Color::Rgb(0xF8, 0x71, 0x71),
                warning: Color::Rgb(0xFB, 0xBF, 0x24),
                info: Color::Rgb(0xA1, 0xA1, 0xAA),
            },
            ThemePreset::NyzhiLight => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(245, 240, 232),
                bg_surface: Color::Rgb(250, 246, 240),
                bg_elevated: Color::Rgb(254, 251, 246),
                bg_sunken: Color::Rgb(237, 231, 220),
                text_primary: Color::Rgb(28, 25, 23),
                text_secondary: Color::Rgb(87, 83, 78),
                text_tertiary: Color::Rgb(135, 130, 124),
                text_disabled: Color::Rgb(214, 211, 209),
                border_default: Color::Rgb(221, 214, 202),
                border_strong: Color::Rgb(207, 198, 184),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(16, 185, 129),
                danger: Color::Rgb(239, 68, 68),
                warning: Color::Rgb(245, 158, 11),
                info: Color::Rgb(113, 113, 122),
            },
            ThemePreset::TokyoNight => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(26, 27, 38),
                bg_surface: Color::Rgb(31, 35, 53),
                bg_elevated: Color::Rgb(36, 40, 59),
                bg_sunken: Color::Rgb(22, 22, 30),
                text_primary: Color::Rgb(192, 202, 245),
                text_secondary: Color::Rgb(169, 177, 214),
                text_tertiary: Color::Rgb(86, 95, 137),
                text_disabled: Color::Rgb(59, 66, 97),
                border_default: Color::Rgb(41, 46, 66),
                border_strong: Color::Rgb(59, 66, 97),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(158, 206, 106),
                danger: Color::Rgb(247, 118, 142),
                warning: Color::Rgb(224, 175, 104),
                info: Color::Rgb(122, 162, 247),
            },
            ThemePreset::CatppuccinMocha => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(30, 30, 46),
                bg_surface: Color::Rgb(49, 50, 68),
                bg_elevated: Color::Rgb(69, 71, 90),
                bg_sunken: Color::Rgb(24, 24, 37),
                text_primary: Color::Rgb(205, 214, 244),
                text_secondary: Color::Rgb(186, 194, 222),
                text_tertiary: Color::Rgb(108, 112, 134),
                text_disabled: Color::Rgb(69, 71, 90),
                border_default: Color::Rgb(49, 50, 68),
                border_strong: Color::Rgb(69, 71, 90),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(166, 227, 161),
                danger: Color::Rgb(243, 139, 168),
                warning: Color::Rgb(249, 226, 175),
                info: Color::Rgb(137, 180, 250),
            },
            ThemePreset::Dracula => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(40, 42, 54),
                bg_surface: Color::Rgb(52, 55, 70),
                bg_elevated: Color::Rgb(68, 71, 90),
                bg_sunken: Color::Rgb(33, 34, 44),
                text_primary: Color::Rgb(248, 248, 242),
                text_secondary: Color::Rgb(189, 192, 208),
                text_tertiary: Color::Rgb(98, 114, 164),
                text_disabled: Color::Rgb(68, 71, 90),
                border_default: Color::Rgb(68, 71, 90),
                border_strong: Color::Rgb(98, 114, 164),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(80, 250, 123),
                danger: Color::Rgb(255, 85, 85),
                warning: Color::Rgb(241, 250, 140),
                info: Color::Rgb(139, 233, 253),
            },
            ThemePreset::SolarizedDark => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(0, 43, 54),
                bg_surface: Color::Rgb(7, 54, 66),
                bg_elevated: Color::Rgb(13, 74, 89),
                bg_sunken: Color::Rgb(0, 30, 38),
                text_primary: Color::Rgb(131, 148, 150),
                text_secondary: Color::Rgb(101, 123, 131),
                text_tertiary: Color::Rgb(88, 110, 117),
                text_disabled: Color::Rgb(46, 79, 88),
                border_default: Color::Rgb(7, 54, 66),
                border_strong: Color::Rgb(88, 110, 117),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(133, 153, 0),
                danger: Color::Rgb(220, 50, 47),
                warning: Color::Rgb(181, 137, 0),
                info: Color::Rgb(38, 139, 210),
            },
            ThemePreset::SolarizedLight => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(253, 246, 227),
                bg_surface: Color::Rgb(255, 249, 237),
                bg_elevated: Color::Rgb(255, 252, 243),
                bg_sunken: Color::Rgb(238, 232, 213),
                text_primary: Color::Rgb(101, 123, 131),
                text_secondary: Color::Rgb(131, 148, 150),
                text_tertiary: Color::Rgb(147, 161, 161),
                text_disabled: Color::Rgb(211, 203, 183),
                border_default: Color::Rgb(238, 232, 213),
                border_strong: Color::Rgb(147, 161, 161),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(133, 153, 0),
                danger: Color::Rgb(220, 50, 47),
                warning: Color::Rgb(181, 137, 0),
                info: Color::Rgb(38, 139, 210),
            },
            ThemePreset::GruvboxDark => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(40, 40, 40),
                bg_surface: Color::Rgb(60, 56, 54),
                bg_elevated: Color::Rgb(80, 73, 69),
                bg_sunken: Color::Rgb(29, 32, 33),
                text_primary: Color::Rgb(235, 219, 178),
                text_secondary: Color::Rgb(213, 196, 161),
                text_tertiary: Color::Rgb(168, 153, 132),
                text_disabled: Color::Rgb(102, 92, 84),
                border_default: Color::Rgb(60, 56, 54),
                border_strong: Color::Rgb(80, 73, 69),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(184, 187, 38),
                danger: Color::Rgb(251, 73, 52),
                warning: Color::Rgb(250, 189, 47),
                info: Color::Rgb(131, 165, 152),
            },
            ThemePreset::CatppuccinLatte => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(239, 241, 245),
                bg_surface: Color::Rgb(230, 233, 239),
                bg_elevated: Color::Rgb(204, 208, 218),
                bg_sunken: Color::Rgb(220, 224, 232),
                text_primary: Color::Rgb(76, 79, 105),
                text_secondary: Color::Rgb(92, 95, 119),
                text_tertiary: Color::Rgb(108, 111, 133),
                text_disabled: Color::Rgb(172, 176, 190),
                border_default: Color::Rgb(204, 208, 218),
                border_strong: Color::Rgb(172, 176, 190),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(64, 160, 43),
                danger: Color::Rgb(210, 15, 57),
                warning: Color::Rgb(223, 142, 29),
                info: Color::Rgb(30, 102, 245),
            },
            ThemePreset::CatppuccinFrappe => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(48, 52, 70),
                bg_surface: Color::Rgb(65, 69, 89),
                bg_elevated: Color::Rgb(81, 87, 109),
                bg_sunken: Color::Rgb(41, 44, 60),
                text_primary: Color::Rgb(198, 208, 245),
                text_secondary: Color::Rgb(181, 191, 226),
                text_tertiary: Color::Rgb(131, 139, 167),
                text_disabled: Color::Rgb(98, 104, 128),
                border_default: Color::Rgb(65, 69, 89),
                border_strong: Color::Rgb(81, 87, 109),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(166, 209, 137),
                danger: Color::Rgb(231, 130, 132),
                warning: Color::Rgb(229, 200, 144),
                info: Color::Rgb(140, 170, 238),
            },
            ThemePreset::CatppuccinMacchiato => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(36, 39, 58),
                bg_surface: Color::Rgb(54, 58, 79),
                bg_elevated: Color::Rgb(73, 77, 100),
                bg_sunken: Color::Rgb(30, 32, 48),
                text_primary: Color::Rgb(202, 211, 245),
                text_secondary: Color::Rgb(184, 192, 224),
                text_tertiary: Color::Rgb(128, 135, 162),
                text_disabled: Color::Rgb(91, 96, 120),
                border_default: Color::Rgb(54, 58, 79),
                border_strong: Color::Rgb(73, 77, 100),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(166, 218, 149),
                danger: Color::Rgb(237, 135, 150),
                warning: Color::Rgb(238, 212, 159),
                info: Color::Rgb(138, 173, 244),
            },
            ThemePreset::Nord => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(46, 52, 64),
                bg_surface: Color::Rgb(59, 66, 82),
                bg_elevated: Color::Rgb(67, 76, 94),
                bg_sunken: Color::Rgb(36, 41, 51),
                text_primary: Color::Rgb(216, 222, 233),
                text_secondary: Color::Rgb(229, 233, 240),
                text_tertiary: Color::Rgb(136, 192, 208),
                text_disabled: Color::Rgb(76, 86, 106),
                border_default: Color::Rgb(59, 66, 82),
                border_strong: Color::Rgb(67, 76, 94),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(163, 190, 140),
                danger: Color::Rgb(191, 97, 106),
                warning: Color::Rgb(235, 203, 139),
                info: Color::Rgb(129, 161, 193),
            },
            ThemePreset::NordLight => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(236, 239, 244),
                bg_surface: Color::Rgb(229, 233, 240),
                bg_elevated: Color::Rgb(216, 222, 233),
                bg_sunken: Color::Rgb(216, 222, 233),
                text_primary: Color::Rgb(46, 52, 64),
                text_secondary: Color::Rgb(59, 66, 82),
                text_tertiary: Color::Rgb(67, 76, 94),
                text_disabled: Color::Rgb(76, 86, 106),
                border_default: Color::Rgb(216, 222, 233),
                border_strong: Color::Rgb(76, 86, 106),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(163, 190, 140),
                danger: Color::Rgb(191, 97, 106),
                warning: Color::Rgb(235, 203, 139),
                info: Color::Rgb(129, 161, 193),
            },
            ThemePreset::RosePine => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(25, 23, 36),
                bg_surface: Color::Rgb(31, 29, 46),
                bg_elevated: Color::Rgb(38, 35, 58),
                bg_sunken: Color::Rgb(21, 19, 30),
                text_primary: Color::Rgb(224, 222, 244),
                text_secondary: Color::Rgb(144, 140, 170),
                text_tertiary: Color::Rgb(110, 106, 134),
                text_disabled: Color::Rgb(82, 79, 103),
                border_default: Color::Rgb(38, 35, 58),
                border_strong: Color::Rgb(57, 53, 82),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(156, 207, 216),
                danger: Color::Rgb(235, 111, 146),
                warning: Color::Rgb(246, 193, 119),
                info: Color::Rgb(196, 167, 231),
            },
            ThemePreset::RosePineMoon => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(35, 33, 54),
                bg_surface: Color::Rgb(42, 39, 63),
                bg_elevated: Color::Rgb(57, 53, 82),
                bg_sunken: Color::Rgb(29, 27, 44),
                text_primary: Color::Rgb(224, 222, 244),
                text_secondary: Color::Rgb(144, 140, 170),
                text_tertiary: Color::Rgb(110, 106, 134),
                text_disabled: Color::Rgb(82, 79, 103),
                border_default: Color::Rgb(42, 39, 63),
                border_strong: Color::Rgb(57, 53, 82),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(156, 207, 216),
                danger: Color::Rgb(235, 111, 146),
                warning: Color::Rgb(246, 193, 119),
                info: Color::Rgb(196, 167, 231),
            },
            ThemePreset::RosePineDawn => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(250, 244, 237),
                bg_surface: Color::Rgb(255, 250, 243),
                bg_elevated: Color::Rgb(242, 233, 222),
                bg_sunken: Color::Rgb(232, 222, 210),
                text_primary: Color::Rgb(87, 82, 121),
                text_secondary: Color::Rgb(121, 117, 147),
                text_tertiary: Color::Rgb(152, 147, 165),
                text_disabled: Color::Rgb(181, 178, 194),
                border_default: Color::Rgb(242, 233, 222),
                border_strong: Color::Rgb(206, 202, 205),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(86, 148, 159),
                danger: Color::Rgb(180, 99, 122),
                warning: Color::Rgb(234, 157, 52),
                info: Color::Rgb(144, 122, 169),
            },
            ThemePreset::Kanagawa => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(31, 31, 40),
                bg_surface: Color::Rgb(43, 43, 57),
                bg_elevated: Color::Rgb(54, 54, 70),
                bg_sunken: Color::Rgb(22, 22, 30),
                text_primary: Color::Rgb(220, 215, 186),
                text_secondary: Color::Rgb(200, 195, 168),
                text_tertiary: Color::Rgb(116, 115, 105),
                text_disabled: Color::Rgb(84, 84, 98),
                border_default: Color::Rgb(43, 43, 57),
                border_strong: Color::Rgb(54, 54, 70),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(152, 195, 121),
                danger: Color::Rgb(195, 64, 67),
                warning: Color::Rgb(255, 160, 102),
                info: Color::Rgb(126, 156, 216),
            },
            ThemePreset::KanagawaLight => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(243, 243, 243),
                bg_surface: Color::Rgb(240, 240, 236),
                bg_elevated: Color::Rgb(228, 228, 224),
                bg_sunken: Color::Rgb(212, 212, 208),
                text_primary: Color::Rgb(31, 31, 40),
                text_secondary: Color::Rgb(43, 43, 57),
                text_tertiary: Color::Rgb(84, 84, 98),
                text_disabled: Color::Rgb(150, 150, 150),
                border_default: Color::Rgb(228, 228, 224),
                border_strong: Color::Rgb(200, 200, 196),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(152, 195, 121),
                danger: Color::Rgb(195, 64, 67),
                warning: Color::Rgb(255, 160, 102),
                info: Color::Rgb(126, 156, 216),
            },
            ThemePreset::EverforestDark => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(47, 53, 47),
                bg_surface: Color::Rgb(52, 59, 53),
                bg_elevated: Color::Rgb(68, 76, 68),
                bg_sunken: Color::Rgb(39, 44, 39),
                text_primary: Color::Rgb(211, 198, 170),
                text_secondary: Color::Rgb(167, 162, 139),
                text_tertiary: Color::Rgb(135, 132, 112),
                text_disabled: Color::Rgb(90, 90, 80),
                border_default: Color::Rgb(62, 69, 62),
                border_strong: Color::Rgb(78, 86, 78),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(167, 192, 128),
                danger: Color::Rgb(230, 126, 128),
                warning: Color::Rgb(219, 188, 127),
                info: Color::Rgb(127, 187, 179),
            },
            ThemePreset::EverforestLight => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(253, 246, 227),
                bg_surface: Color::Rgb(243, 236, 215),
                bg_elevated: Color::Rgb(235, 228, 207),
                bg_sunken: Color::Rgb(231, 224, 203),
                text_primary: Color::Rgb(92, 91, 75),
                text_secondary: Color::Rgb(106, 105, 88),
                text_tertiary: Color::Rgb(130, 129, 115),
                text_disabled: Color::Rgb(174, 173, 161),
                border_default: Color::Rgb(221, 214, 195),
                border_strong: Color::Rgb(195, 188, 170),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(141, 165, 83),
                danger: Color::Rgb(241, 96, 79),
                warning: Color::Rgb(220, 171, 64),
                info: Color::Rgb(75, 161, 148),
            },
            ThemePreset::AyuDark => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(11, 14, 20),
                bg_surface: Color::Rgb(15, 20, 29),
                bg_elevated: Color::Rgb(23, 29, 41),
                bg_sunken: Color::Rgb(7, 10, 15),
                text_primary: Color::Rgb(191, 199, 213),
                text_secondary: Color::Rgb(140, 149, 167),
                text_tertiary: Color::Rgb(95, 103, 117),
                text_disabled: Color::Rgb(62, 68, 81),
                border_default: Color::Rgb(23, 29, 41),
                border_strong: Color::Rgb(42, 49, 63),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(122, 203, 134),
                danger: Color::Rgb(255, 51, 51),
                warning: Color::Rgb(255, 180, 84),
                info: Color::Rgb(57, 186, 230),
            },
            ThemePreset::AyuLight => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(250, 250, 250),
                bg_surface: Color::Rgb(242, 243, 245),
                bg_elevated: Color::Rgb(232, 233, 235),
                bg_sunken: Color::Rgb(222, 223, 225),
                text_primary: Color::Rgb(91, 97, 105),
                text_secondary: Color::Rgb(116, 122, 130),
                text_tertiary: Color::Rgb(141, 147, 155),
                text_disabled: Color::Rgb(182, 187, 194),
                border_default: Color::Rgb(222, 223, 225),
                border_strong: Color::Rgb(190, 192, 197),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(108, 179, 63),
                danger: Color::Rgb(240, 113, 120),
                warning: Color::Rgb(244, 168, 52),
                info: Color::Rgb(57, 171, 215),
            },
            ThemePreset::AyuMirage => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(29, 32, 42),
                bg_surface: Color::Rgb(36, 40, 53),
                bg_elevated: Color::Rgb(47, 52, 67),
                bg_sunken: Color::Rgb(23, 26, 34),
                text_primary: Color::Rgb(203, 206, 218),
                text_secondary: Color::Rgb(157, 161, 177),
                text_tertiary: Color::Rgb(115, 120, 137),
                text_disabled: Color::Rgb(75, 79, 93),
                border_default: Color::Rgb(36, 40, 53),
                border_strong: Color::Rgb(47, 52, 67),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(135, 201, 135),
                danger: Color::Rgb(255, 101, 101),
                warning: Color::Rgb(255, 211, 108),
                info: Color::Rgb(92, 182, 229),
            },
            ThemePreset::OneDark => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(40, 44, 52),
                bg_surface: Color::Rgb(48, 52, 62),
                bg_elevated: Color::Rgb(55, 60, 72),
                bg_sunken: Color::Rgb(33, 37, 43),
                text_primary: Color::Rgb(171, 178, 191),
                text_secondary: Color::Rgb(152, 159, 172),
                text_tertiary: Color::Rgb(92, 99, 112),
                text_disabled: Color::Rgb(65, 71, 82),
                border_default: Color::Rgb(48, 52, 62),
                border_strong: Color::Rgb(65, 71, 82),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(152, 195, 121),
                danger: Color::Rgb(224, 108, 117),
                warning: Color::Rgb(229, 192, 123),
                info: Color::Rgb(97, 175, 239),
            },
            ThemePreset::OneLight => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(250, 250, 250),
                bg_surface: Color::Rgb(240, 240, 240),
                bg_elevated: Color::Rgb(226, 226, 226),
                bg_sunken: Color::Rgb(219, 220, 221),
                text_primary: Color::Rgb(56, 58, 66),
                text_secondary: Color::Rgb(80, 82, 92),
                text_tertiary: Color::Rgb(110, 112, 122),
                text_disabled: Color::Rgb(176, 178, 185),
                border_default: Color::Rgb(219, 220, 221),
                border_strong: Color::Rgb(176, 178, 185),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(80, 161, 79),
                danger: Color::Rgb(228, 86, 73),
                warning: Color::Rgb(193, 132, 1),
                info: Color::Rgb(64, 120, 242),
            },
            ThemePreset::NightOwl => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(1, 22, 39),
                bg_surface: Color::Rgb(1, 32, 52),
                bg_elevated: Color::Rgb(8, 44, 68),
                bg_sunken: Color::Rgb(0, 16, 30),
                text_primary: Color::Rgb(214, 222, 235),
                text_secondary: Color::Rgb(176, 185, 200),
                text_tertiary: Color::Rgb(107, 126, 141),
                text_disabled: Color::Rgb(68, 85, 100),
                border_default: Color::Rgb(16, 44, 64),
                border_strong: Color::Rgb(32, 60, 82),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(34, 209, 170),
                danger: Color::Rgb(239, 83, 80),
                warning: Color::Rgb(255, 203, 107),
                info: Color::Rgb(130, 170, 255),
            },
            ThemePreset::NightOwlLight => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(251, 251, 251),
                bg_surface: Color::Rgb(243, 244, 246),
                bg_elevated: Color::Rgb(227, 229, 234),
                bg_sunken: Color::Rgb(218, 220, 224),
                text_primary: Color::Rgb(64, 63, 83),
                text_secondary: Color::Rgb(90, 89, 108),
                text_tertiary: Color::Rgb(120, 119, 138),
                text_disabled: Color::Rgb(170, 170, 182),
                border_default: Color::Rgb(227, 229, 234),
                border_strong: Color::Rgb(195, 197, 203),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(8, 148, 108),
                danger: Color::Rgb(222, 35, 42),
                warning: Color::Rgb(218, 143, 6),
                info: Color::Rgb(68, 95, 182),
            },
            ThemePreset::MaterialDarker => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(33, 33, 33),
                bg_surface: Color::Rgb(42, 42, 42),
                bg_elevated: Color::Rgb(55, 55, 55),
                bg_sunken: Color::Rgb(24, 24, 24),
                text_primary: Color::Rgb(238, 238, 238),
                text_secondary: Color::Rgb(178, 178, 178),
                text_tertiary: Color::Rgb(112, 112, 112),
                text_disabled: Color::Rgb(68, 68, 68),
                border_default: Color::Rgb(42, 42, 42),
                border_strong: Color::Rgb(55, 55, 55),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(195, 232, 141),
                danger: Color::Rgb(255, 83, 112),
                warning: Color::Rgb(255, 203, 107),
                info: Color::Rgb(130, 170, 255),
            },
            ThemePreset::MaterialOcean => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(15, 17, 26),
                bg_surface: Color::Rgb(26, 29, 42),
                bg_elevated: Color::Rgb(38, 42, 58),
                bg_sunken: Color::Rgb(10, 12, 18),
                text_primary: Color::Rgb(166, 172, 205),
                text_secondary: Color::Rgb(139, 145, 176),
                text_tertiary: Color::Rgb(96, 103, 137),
                text_disabled: Color::Rgb(64, 69, 96),
                border_default: Color::Rgb(26, 29, 42),
                border_strong: Color::Rgb(38, 42, 58),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(195, 232, 141),
                danger: Color::Rgb(255, 83, 112),
                warning: Color::Rgb(255, 203, 107),
                info: Color::Rgb(130, 170, 255),
            },
            ThemePreset::MaterialPalenight => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(41, 45, 62),
                bg_surface: Color::Rgb(52, 56, 76),
                bg_elevated: Color::Rgb(66, 71, 93),
                bg_sunken: Color::Rgb(32, 35, 48),
                text_primary: Color::Rgb(166, 172, 205),
                text_secondary: Color::Rgb(139, 145, 176),
                text_tertiary: Color::Rgb(96, 103, 137),
                text_disabled: Color::Rgb(64, 69, 96),
                border_default: Color::Rgb(52, 56, 76),
                border_strong: Color::Rgb(66, 71, 93),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(195, 232, 141),
                danger: Color::Rgb(255, 83, 112),
                warning: Color::Rgb(255, 203, 107),
                info: Color::Rgb(130, 170, 255),
            },
            ThemePreset::GitHubDark => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(13, 17, 23),
                bg_surface: Color::Rgb(22, 27, 34),
                bg_elevated: Color::Rgb(33, 38, 47),
                bg_sunken: Color::Rgb(1, 4, 9),
                text_primary: Color::Rgb(230, 237, 243),
                text_secondary: Color::Rgb(139, 148, 158),
                text_tertiary: Color::Rgb(110, 118, 129),
                text_disabled: Color::Rgb(72, 79, 88),
                border_default: Color::Rgb(33, 38, 47),
                border_strong: Color::Rgb(52, 59, 66),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(63, 185, 80),
                danger: Color::Rgb(248, 81, 73),
                warning: Color::Rgb(210, 153, 34),
                info: Color::Rgb(88, 166, 255),
            },
            ThemePreset::GitHubLight => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(255, 255, 255),
                bg_surface: Color::Rgb(246, 248, 250),
                bg_elevated: Color::Rgb(234, 238, 242),
                bg_sunken: Color::Rgb(210, 215, 220),
                text_primary: Color::Rgb(31, 35, 40),
                text_secondary: Color::Rgb(87, 96, 106),
                text_tertiary: Color::Rgb(110, 119, 129),
                text_disabled: Color::Rgb(175, 184, 193),
                border_default: Color::Rgb(216, 222, 228),
                border_strong: Color::Rgb(175, 184, 193),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(26, 127, 55),
                danger: Color::Rgb(207, 34, 46),
                warning: Color::Rgb(155, 103, 0),
                info: Color::Rgb(9, 105, 218),
            },
            ThemePreset::GitHubDimmed => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(34, 39, 46),
                bg_surface: Color::Rgb(44, 50, 58),
                bg_elevated: Color::Rgb(56, 63, 72),
                bg_sunken: Color::Rgb(22, 27, 34),
                text_primary: Color::Rgb(173, 186, 199),
                text_secondary: Color::Rgb(139, 148, 158),
                text_tertiary: Color::Rgb(110, 118, 129),
                text_disabled: Color::Rgb(72, 79, 88),
                border_default: Color::Rgb(56, 63, 72),
                border_strong: Color::Rgb(72, 79, 88),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(87, 171, 90),
                danger: Color::Rgb(248, 81, 73),
                warning: Color::Rgb(187, 128, 9),
                info: Color::Rgb(78, 156, 240),
            },
            ThemePreset::Nightfox => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(25, 28, 39),
                bg_surface: Color::Rgb(33, 37, 51),
                bg_elevated: Color::Rgb(43, 48, 65),
                bg_sunken: Color::Rgb(18, 20, 28),
                text_primary: Color::Rgb(205, 214, 244),
                text_secondary: Color::Rgb(155, 163, 191),
                text_tertiary: Color::Rgb(113, 120, 149),
                text_disabled: Color::Rgb(78, 85, 112),
                border_default: Color::Rgb(43, 48, 65),
                border_strong: Color::Rgb(60, 66, 88),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(129, 200, 190),
                danger: Color::Rgb(195, 64, 67),
                warning: Color::Rgb(218, 168, 82),
                info: Color::Rgb(125, 174, 228),
            },
            ThemePreset::Dawnfox => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(250, 244, 237),
                bg_surface: Color::Rgb(242, 236, 225),
                bg_elevated: Color::Rgb(232, 226, 215),
                bg_sunken: Color::Rgb(222, 216, 205),
                text_primary: Color::Rgb(41, 44, 60),
                text_secondary: Color::Rgb(87, 82, 121),
                text_tertiary: Color::Rgb(121, 117, 147),
                text_disabled: Color::Rgb(181, 178, 194),
                border_default: Color::Rgb(222, 216, 205),
                border_strong: Color::Rgb(196, 190, 180),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(86, 148, 159),
                danger: Color::Rgb(180, 99, 122),
                warning: Color::Rgb(234, 157, 52),
                info: Color::Rgb(40, 105, 131),
            },
            ThemePreset::Carbonfox => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(22, 22, 22),
                bg_surface: Color::Rgb(33, 33, 33),
                bg_elevated: Color::Rgb(44, 44, 44),
                bg_sunken: Color::Rgb(15, 15, 15),
                text_primary: Color::Rgb(240, 240, 240),
                text_secondary: Color::Rgb(177, 177, 177),
                text_tertiary: Color::Rgb(124, 124, 124),
                text_disabled: Color::Rgb(82, 82, 82),
                border_default: Color::Rgb(44, 44, 44),
                border_strong: Color::Rgb(60, 60, 60),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(37, 194, 111),
                danger: Color::Rgb(238, 75, 43),
                warning: Color::Rgb(254, 215, 0),
                info: Color::Rgb(120, 160, 246),
            },
            ThemePreset::MonokaiPro => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(45, 42, 46),
                bg_surface: Color::Rgb(55, 52, 56),
                bg_elevated: Color::Rgb(65, 63, 67),
                bg_sunken: Color::Rgb(36, 33, 37),
                text_primary: Color::Rgb(252, 252, 250),
                text_secondary: Color::Rgb(200, 197, 201),
                text_tertiary: Color::Rgb(147, 146, 147),
                text_disabled: Color::Rgb(100, 99, 100),
                border_default: Color::Rgb(55, 52, 56),
                border_strong: Color::Rgb(65, 63, 67),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(166, 226, 46),
                danger: Color::Rgb(249, 38, 114),
                warning: Color::Rgb(230, 219, 116),
                info: Color::Rgb(102, 217, 239),
            },
            ThemePreset::MonokaiClassic => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(39, 40, 34),
                bg_surface: Color::Rgb(49, 50, 44),
                bg_elevated: Color::Rgb(58, 60, 54),
                bg_sunken: Color::Rgb(30, 31, 25),
                text_primary: Color::Rgb(248, 248, 242),
                text_secondary: Color::Rgb(200, 200, 193),
                text_tertiary: Color::Rgb(117, 113, 94),
                text_disabled: Color::Rgb(68, 68, 60),
                border_default: Color::Rgb(49, 50, 44),
                border_strong: Color::Rgb(58, 60, 54),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(166, 226, 46),
                danger: Color::Rgb(249, 38, 114),
                warning: Color::Rgb(230, 219, 116),
                info: Color::Rgb(102, 217, 239),
            },
            ThemePreset::Sonokai => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(43, 43, 43),
                bg_surface: Color::Rgb(55, 55, 55),
                bg_elevated: Color::Rgb(65, 65, 65),
                bg_sunken: Color::Rgb(33, 33, 33),
                text_primary: Color::Rgb(227, 225, 221),
                text_secondary: Color::Rgb(190, 188, 184),
                text_tertiary: Color::Rgb(130, 128, 124),
                text_disabled: Color::Rgb(85, 85, 85),
                border_default: Color::Rgb(55, 55, 55),
                border_strong: Color::Rgb(68, 68, 68),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(157, 212, 109),
                danger: Color::Rgb(252, 91, 122),
                warning: Color::Rgb(224, 178, 67),
                info: Color::Rgb(118, 173, 235),
            },
            ThemePreset::Moonfly => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(8, 8, 8),
                bg_surface: Color::Rgb(18, 18, 18),
                bg_elevated: Color::Rgb(28, 28, 28),
                bg_sunken: Color::Rgb(3, 3, 3),
                text_primary: Color::Rgb(189, 189, 189),
                text_secondary: Color::Rgb(158, 158, 158),
                text_tertiary: Color::Rgb(108, 108, 108),
                text_disabled: Color::Rgb(68, 68, 68),
                border_default: Color::Rgb(28, 28, 28),
                border_strong: Color::Rgb(48, 48, 48),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(130, 206, 140),
                danger: Color::Rgb(255, 92, 87),
                warning: Color::Rgb(228, 208, 108),
                info: Color::Rgb(128, 180, 246),
            },
            ThemePreset::Nightfly => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(1, 13, 32),
                bg_surface: Color::Rgb(5, 22, 48),
                bg_elevated: Color::Rgb(12, 34, 60),
                bg_sunken: Color::Rgb(0, 8, 22),
                text_primary: Color::Rgb(195, 207, 225),
                text_secondary: Color::Rgb(162, 175, 194),
                text_tertiary: Color::Rgb(118, 131, 150),
                text_disabled: Color::Rgb(72, 85, 104),
                border_default: Color::Rgb(12, 34, 60),
                border_strong: Color::Rgb(28, 50, 78),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(33, 209, 170),
                danger: Color::Rgb(252, 105, 98),
                warning: Color::Rgb(224, 204, 104),
                info: Color::Rgb(130, 173, 255),
            },
            ThemePreset::NoctisAzureus => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(3, 22, 52),
                bg_surface: Color::Rgb(6, 34, 72),
                bg_elevated: Color::Rgb(15, 46, 88),
                bg_sunken: Color::Rgb(0, 14, 36),
                text_primary: Color::Rgb(206, 222, 243),
                text_secondary: Color::Rgb(169, 186, 208),
                text_tertiary: Color::Rgb(113, 138, 168),
                text_disabled: Color::Rgb(72, 92, 118),
                border_default: Color::Rgb(15, 46, 88),
                border_strong: Color::Rgb(30, 60, 100),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(73, 215, 143),
                danger: Color::Rgb(255, 100, 100),
                warning: Color::Rgb(255, 199, 79),
                info: Color::Rgb(122, 168, 255),
            },
            ThemePreset::NoctisLux => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(254, 246, 225),
                bg_surface: Color::Rgb(248, 240, 210),
                bg_elevated: Color::Rgb(238, 230, 200),
                bg_sunken: Color::Rgb(228, 220, 195),
                text_primary: Color::Rgb(66, 60, 48),
                text_secondary: Color::Rgb(100, 94, 82),
                text_tertiary: Color::Rgb(130, 124, 112),
                text_disabled: Color::Rgb(170, 165, 155),
                border_default: Color::Rgb(228, 220, 195),
                border_strong: Color::Rgb(200, 192, 170),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(70, 135, 62),
                danger: Color::Rgb(210, 60, 60),
                warning: Color::Rgb(197, 145, 38),
                info: Color::Rgb(50, 100, 165),
            },
            ThemePreset::Zenbones => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(25, 25, 25),
                bg_surface: Color::Rgb(35, 35, 35),
                bg_elevated: Color::Rgb(48, 48, 48),
                bg_sunken: Color::Rgb(18, 18, 18),
                text_primary: Color::Rgb(187, 176, 163),
                text_secondary: Color::Rgb(158, 148, 136),
                text_tertiary: Color::Rgb(120, 112, 102),
                text_disabled: Color::Rgb(78, 73, 66),
                border_default: Color::Rgb(40, 40, 40),
                border_strong: Color::Rgb(56, 56, 56),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(129, 161, 110),
                danger: Color::Rgb(222, 104, 104),
                warning: Color::Rgb(205, 163, 88),
                info: Color::Rgb(105, 138, 167),
            },
            ThemePreset::Zenwritten => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(245, 240, 232),
                bg_surface: Color::Rgb(238, 233, 225),
                bg_elevated: Color::Rgb(228, 223, 215),
                bg_sunken: Color::Rgb(218, 213, 205),
                text_primary: Color::Rgb(55, 50, 43),
                text_secondary: Color::Rgb(85, 80, 73),
                text_tertiary: Color::Rgb(120, 115, 108),
                text_disabled: Color::Rgb(172, 168, 162),
                border_default: Color::Rgb(218, 213, 205),
                border_strong: Color::Rgb(195, 190, 183),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(92, 128, 78),
                danger: Color::Rgb(168, 62, 62),
                warning: Color::Rgb(165, 118, 45),
                info: Color::Rgb(75, 105, 130),
            },
            ThemePreset::MinDark => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(20, 20, 20),
                bg_surface: Color::Rgb(30, 30, 30),
                bg_elevated: Color::Rgb(42, 42, 42),
                bg_sunken: Color::Rgb(14, 14, 14),
                text_primary: Color::Rgb(228, 228, 228),
                text_secondary: Color::Rgb(180, 180, 180),
                text_tertiary: Color::Rgb(120, 120, 120),
                text_disabled: Color::Rgb(70, 70, 70),
                border_default: Color::Rgb(36, 36, 36),
                border_strong: Color::Rgb(52, 52, 52),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(74, 222, 128),
                danger: Color::Rgb(248, 113, 113),
                warning: Color::Rgb(251, 191, 36),
                info: Color::Rgb(161, 161, 170),
            },
            ThemePreset::MinLight => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(255, 255, 255),
                bg_surface: Color::Rgb(246, 246, 246),
                bg_elevated: Color::Rgb(234, 234, 234),
                bg_sunken: Color::Rgb(224, 224, 224),
                text_primary: Color::Rgb(30, 30, 30),
                text_secondary: Color::Rgb(80, 80, 80),
                text_tertiary: Color::Rgb(130, 130, 130),
                text_disabled: Color::Rgb(185, 185, 185),
                border_default: Color::Rgb(224, 224, 224),
                border_strong: Color::Rgb(190, 190, 190),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(16, 185, 129),
                danger: Color::Rgb(239, 68, 68),
                warning: Color::Rgb(245, 158, 11),
                info: Color::Rgb(113, 113, 122),
            },
            ThemePreset::Panda => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(41, 45, 62),
                bg_surface: Color::Rgb(55, 61, 79),
                bg_elevated: Color::Rgb(69, 76, 97),
                bg_sunken: Color::Rgb(32, 35, 48),
                text_primary: Color::Rgb(230, 232, 236),
                text_secondary: Color::Rgb(189, 191, 196),
                text_tertiary: Color::Rgb(123, 125, 132),
                text_disabled: Color::Rgb(82, 84, 91),
                border_default: Color::Rgb(55, 61, 79),
                border_strong: Color::Rgb(82, 88, 106),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(25, 185, 154),
                danger: Color::Rgb(255, 117, 137),
                warning: Color::Rgb(255, 184, 108),
                info: Color::Rgb(103, 177, 255),
            },
            ThemePreset::Synthwave84 => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(38, 20, 71),
                bg_surface: Color::Rgb(48, 30, 82),
                bg_elevated: Color::Rgb(62, 42, 98),
                bg_sunken: Color::Rgb(28, 14, 55),
                text_primary: Color::Rgb(255, 230, 245),
                text_secondary: Color::Rgb(220, 195, 215),
                text_tertiary: Color::Rgb(160, 135, 170),
                text_disabled: Color::Rgb(100, 80, 115),
                border_default: Color::Rgb(62, 42, 98),
                border_strong: Color::Rgb(85, 60, 125),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(114, 255, 188),
                danger: Color::Rgb(254, 66, 118),
                warning: Color::Rgb(254, 211, 59),
                info: Color::Rgb(54, 206, 236),
            },
            ThemePreset::Cobalt2 => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(25, 32, 52),
                bg_surface: Color::Rgb(33, 42, 65),
                bg_elevated: Color::Rgb(48, 58, 82),
                bg_sunken: Color::Rgb(18, 24, 40),
                text_primary: Color::Rgb(255, 255, 255),
                text_secondary: Color::Rgb(190, 195, 205),
                text_tertiary: Color::Rgb(120, 130, 150),
                text_disabled: Color::Rgb(75, 85, 105),
                border_default: Color::Rgb(40, 50, 72),
                border_strong: Color::Rgb(55, 66, 90),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(58, 255, 168),
                danger: Color::Rgb(255, 36, 82),
                warning: Color::Rgb(255, 200, 40),
                info: Color::Rgb(128, 216, 255),
            },
            ThemePreset::Andromeda => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(35, 36, 44),
                bg_surface: Color::Rgb(44, 46, 55),
                bg_elevated: Color::Rgb(56, 58, 69),
                bg_sunken: Color::Rgb(28, 29, 36),
                text_primary: Color::Rgb(214, 215, 225),
                text_secondary: Color::Rgb(172, 174, 186),
                text_tertiary: Color::Rgb(114, 116, 128),
                text_disabled: Color::Rgb(74, 76, 86),
                border_default: Color::Rgb(44, 46, 55),
                border_strong: Color::Rgb(68, 70, 82),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(150, 224, 114),
                danger: Color::Rgb(238, 74, 93),
                warning: Color::Rgb(246, 196, 83),
                info: Color::Rgb(112, 186, 232),
            },
            ThemePreset::ShadesOfPurple => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(30, 30, 56),
                bg_surface: Color::Rgb(40, 40, 72),
                bg_elevated: Color::Rgb(55, 55, 90),
                bg_sunken: Color::Rgb(22, 22, 42),
                text_primary: Color::Rgb(255, 255, 255),
                text_secondary: Color::Rgb(190, 185, 210),
                text_tertiary: Color::Rgb(140, 136, 168),
                text_disabled: Color::Rgb(90, 88, 112),
                border_default: Color::Rgb(50, 50, 82),
                border_strong: Color::Rgb(70, 70, 105),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(168, 255, 96),
                danger: Color::Rgb(255, 78, 113),
                warning: Color::Rgb(255, 200, 40),
                info: Color::Rgb(156, 220, 254),
            },
            ThemePreset::Iceberg => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(22, 26, 34),
                bg_surface: Color::Rgb(29, 35, 44),
                bg_elevated: Color::Rgb(37, 44, 56),
                bg_sunken: Color::Rgb(16, 20, 26),
                text_primary: Color::Rgb(197, 200, 210),
                text_secondary: Color::Rgb(156, 160, 172),
                text_tertiary: Color::Rgb(109, 117, 131),
                text_disabled: Color::Rgb(72, 78, 90),
                border_default: Color::Rgb(37, 44, 56),
                border_strong: Color::Rgb(52, 60, 72),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(176, 211, 137),
                danger: Color::Rgb(226, 120, 120),
                warning: Color::Rgb(225, 195, 130),
                info: Color::Rgb(132, 167, 207),
            },
            ThemePreset::GruvboxLight => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(251, 241, 199),
                bg_surface: Color::Rgb(242, 229, 188),
                bg_elevated: Color::Rgb(230, 218, 176),
                bg_sunken: Color::Rgb(213, 196, 161),
                text_primary: Color::Rgb(60, 56, 54),
                text_secondary: Color::Rgb(80, 73, 69),
                text_tertiary: Color::Rgb(102, 92, 84),
                text_disabled: Color::Rgb(168, 153, 132),
                border_default: Color::Rgb(213, 196, 161),
                border_strong: Color::Rgb(168, 153, 132),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(121, 116, 14),
                danger: Color::Rgb(204, 36, 29),
                warning: Color::Rgb(215, 153, 33),
                info: Color::Rgb(69, 133, 136),
            },
            ThemePreset::Srcery => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(28, 27, 25),
                bg_surface: Color::Rgb(38, 37, 35),
                bg_elevated: Color::Rgb(50, 49, 47),
                bg_sunken: Color::Rgb(20, 19, 18),
                text_primary: Color::Rgb(252, 232, 195),
                text_secondary: Color::Rgb(213, 196, 161),
                text_tertiary: Color::Rgb(153, 142, 120),
                text_disabled: Color::Rgb(96, 88, 72),
                border_default: Color::Rgb(50, 49, 47),
                border_strong: Color::Rgb(68, 65, 58),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(152, 197, 45),
                danger: Color::Rgb(239, 47, 39),
                warning: Color::Rgb(254, 178, 0),
                info: Color::Rgb(72, 131, 171),
            },
            ThemePreset::WinterDark => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(13, 17, 24),
                bg_surface: Color::Rgb(22, 27, 37),
                bg_elevated: Color::Rgb(34, 42, 54),
                bg_sunken: Color::Rgb(8, 10, 16),
                text_primary: Color::Rgb(212, 224, 240),
                text_secondary: Color::Rgb(171, 183, 200),
                text_tertiary: Color::Rgb(118, 132, 152),
                text_disabled: Color::Rgb(72, 85, 104),
                border_default: Color::Rgb(34, 42, 54),
                border_strong: Color::Rgb(50, 60, 76),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(86, 199, 148),
                danger: Color::Rgb(255, 107, 107),
                warning: Color::Rgb(255, 199, 95),
                info: Color::Rgb(103, 178, 255),
            },
            ThemePreset::WinterLight => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(248, 250, 252),
                bg_surface: Color::Rgb(240, 243, 247),
                bg_elevated: Color::Rgb(228, 232, 238),
                bg_sunken: Color::Rgb(218, 222, 228),
                text_primary: Color::Rgb(42, 50, 62),
                text_secondary: Color::Rgb(72, 82, 96),
                text_tertiary: Color::Rgb(108, 118, 132),
                text_disabled: Color::Rgb(165, 175, 190),
                border_default: Color::Rgb(218, 222, 228),
                border_strong: Color::Rgb(190, 196, 205),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(44, 145, 94),
                danger: Color::Rgb(205, 68, 68),
                warning: Color::Rgb(186, 128, 12),
                info: Color::Rgb(55, 118, 200),
            },
            ThemePreset::Tender => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(40, 40, 40),
                bg_surface: Color::Rgb(50, 50, 50),
                bg_elevated: Color::Rgb(65, 65, 65),
                bg_sunken: Color::Rgb(30, 30, 30),
                text_primary: Color::Rgb(238, 238, 238),
                text_secondary: Color::Rgb(195, 195, 195),
                text_tertiary: Color::Rgb(140, 140, 140),
                text_disabled: Color::Rgb(85, 85, 85),
                border_default: Color::Rgb(50, 50, 50),
                border_strong: Color::Rgb(68, 68, 68),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(195, 223, 147),
                danger: Color::Rgb(243, 131, 131),
                warning: Color::Rgb(234, 185, 96),
                info: Color::Rgb(181, 205, 237),
            },
            ThemePreset::Vesper => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(16, 16, 20),
                bg_surface: Color::Rgb(24, 24, 30),
                bg_elevated: Color::Rgb(35, 35, 42),
                bg_sunken: Color::Rgb(10, 10, 14),
                text_primary: Color::Rgb(205, 205, 195),
                text_secondary: Color::Rgb(160, 160, 150),
                text_tertiary: Color::Rgb(110, 110, 102),
                text_disabled: Color::Rgb(68, 68, 62),
                border_default: Color::Rgb(30, 30, 38),
                border_strong: Color::Rgb(48, 48, 56),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(166, 227, 161),
                danger: Color::Rgb(246, 115, 130),
                warning: Color::Rgb(255, 198, 109),
                info: Color::Rgb(155, 185, 225),
            },
            ThemePreset::Apprentice => Theme {
                mode,
                preset: self,
                accent_type: accent,
                bg_page: Color::Rgb(28, 28, 28),
                bg_surface: Color::Rgb(40, 40, 40),
                bg_elevated: Color::Rgb(54, 54, 54),
                bg_sunken: Color::Rgb(20, 20, 20),
                text_primary: Color::Rgb(188, 188, 188),
                text_secondary: Color::Rgb(148, 148, 148),
                text_tertiary: Color::Rgb(108, 108, 108),
                text_disabled: Color::Rgb(68, 68, 68),
                border_default: Color::Rgb(44, 44, 44),
                border_strong: Color::Rgb(62, 62, 62),
                accent: accent.color(mode),
                accent_muted: accent.muted(mode),
                success: Color::Rgb(135, 175, 95),
                danger: Color::Rgb(175, 95, 95),
                warning: Color::Rgb(215, 175, 95),
                info: Color::Rgb(95, 135, 175),
            },
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Accent {
    NyzhiOrange,
    Copper,
    Blue,
    Orange,
    Emerald,
    Violet,
    Rose,
    Amber,
    Cyan,
    Red,
    Pink,
    Teal,
    Indigo,
    Lime,
    Monochrome,
    Gold,
    Coral,
    Peach,
    Tangerine,
    Salmon,
    Sunset,
    Bronze,
    Lavender,
    Mint,
    Sky,
    Frost,
    Periwinkle,
    Steel,
    Lilac,
    Ruby,
    Sapphire,
    Jade,
    Crimson,
    Magenta,
    Plum,
    Mauve,
    Sage,
    Forest,
    Olive,
    Maroon,
    Slate,
    Topaz,
    Turquoise,
    Chartreuse,
    Midnight,
}

impl Accent {
    pub const ALL: &[Accent] = &[
        Accent::NyzhiOrange,
        Accent::Copper,
        Accent::Blue,
        Accent::Orange,
        Accent::Emerald,
        Accent::Violet,
        Accent::Rose,
        Accent::Amber,
        Accent::Cyan,
        Accent::Red,
        Accent::Pink,
        Accent::Teal,
        Accent::Indigo,
        Accent::Lime,
        Accent::Monochrome,
        Accent::Gold,
        Accent::Coral,
        Accent::Peach,
        Accent::Tangerine,
        Accent::Salmon,
        Accent::Sunset,
        Accent::Bronze,
        Accent::Lavender,
        Accent::Mint,
        Accent::Sky,
        Accent::Frost,
        Accent::Periwinkle,
        Accent::Steel,
        Accent::Lilac,
        Accent::Ruby,
        Accent::Sapphire,
        Accent::Jade,
        Accent::Crimson,
        Accent::Magenta,
        Accent::Plum,
        Accent::Mauve,
        Accent::Sage,
        Accent::Forest,
        Accent::Olive,
        Accent::Maroon,
        Accent::Slate,
        Accent::Topaz,
        Accent::Turquoise,
        Accent::Chartreuse,
        Accent::Midnight,
    ];

    pub fn name(self) -> &'static str {
        match self {
            Accent::NyzhiOrange => "nyzhi-orange",
            Accent::Copper => "copper",
            Accent::Blue => "blue",
            Accent::Orange => "orange",
            Accent::Emerald => "emerald",
            Accent::Violet => "violet",
            Accent::Rose => "rose",
            Accent::Amber => "amber",
            Accent::Cyan => "cyan",
            Accent::Red => "red",
            Accent::Pink => "pink",
            Accent::Teal => "teal",
            Accent::Indigo => "indigo",
            Accent::Lime => "lime",
            Accent::Monochrome => "monochrome",
            Accent::Gold => "gold",
            Accent::Coral => "coral",
            Accent::Peach => "peach",
            Accent::Tangerine => "tangerine",
            Accent::Salmon => "salmon",
            Accent::Sunset => "sunset",
            Accent::Bronze => "bronze",
            Accent::Lavender => "lavender",
            Accent::Mint => "mint",
            Accent::Sky => "sky",
            Accent::Frost => "frost",
            Accent::Periwinkle => "periwinkle",
            Accent::Steel => "steel",
            Accent::Lilac => "lilac",
            Accent::Ruby => "ruby",
            Accent::Sapphire => "sapphire",
            Accent::Jade => "jade",
            Accent::Crimson => "crimson",
            Accent::Magenta => "magenta",
            Accent::Plum => "plum",
            Accent::Mauve => "mauve",
            Accent::Sage => "sage",
            Accent::Forest => "forest",
            Accent::Olive => "olive",
            Accent::Maroon => "maroon",
            Accent::Slate => "slate",
            Accent::Topaz => "topaz",
            Accent::Turquoise => "turquoise",
            Accent::Chartreuse => "chartreuse",
            Accent::Midnight => "midnight",
        }
    }

    pub fn from_name(name: &str) -> Self {
        match name.to_lowercase().as_str() {
            "nyzhi-orange" | "nyzhi_orange" | "nyzhiorange" | "orange-nyzhi" => Accent::NyzhiOrange,
            "copper" => Accent::Copper,
            "blue" => Accent::Blue,
            "orange" => Accent::Orange,
            "emerald" => Accent::Emerald,
            "violet" => Accent::Violet,
            "rose" => Accent::Rose,
            "amber" => Accent::Amber,
            "cyan" => Accent::Cyan,
            "red" => Accent::Red,
            "pink" => Accent::Pink,
            "teal" => Accent::Teal,
            "indigo" => Accent::Indigo,
            "lime" => Accent::Lime,
            "monochrome" => Accent::Monochrome,
            "gold" => Accent::Gold,
            "coral" => Accent::Coral,
            "peach" => Accent::Peach,
            "tangerine" => Accent::Tangerine,
            "salmon" => Accent::Salmon,
            "sunset" => Accent::Sunset,
            "bronze" => Accent::Bronze,
            "lavender" => Accent::Lavender,
            "mint" => Accent::Mint,
            "sky" => Accent::Sky,
            "frost" => Accent::Frost,
            "periwinkle" => Accent::Periwinkle,
            "steel" => Accent::Steel,
            "lilac" => Accent::Lilac,
            "ruby" => Accent::Ruby,
            "sapphire" => Accent::Sapphire,
            "jade" => Accent::Jade,
            "crimson" => Accent::Crimson,
            "magenta" => Accent::Magenta,
            "plum" => Accent::Plum,
            "mauve" => Accent::Mauve,
            "sage" => Accent::Sage,
            "forest" => Accent::Forest,
            "olive" => Accent::Olive,
            "maroon" => Accent::Maroon,
            "slate" => Accent::Slate,
            "topaz" => Accent::Topaz,
            "turquoise" => Accent::Turquoise,
            "chartreuse" => Accent::Chartreuse,
            "midnight" => Accent::Midnight,
            _ => Accent::NyzhiOrange,
        }
    }

    pub fn next(self) -> Self {
        let idx = Accent::ALL.iter().position(|&a| a == self).unwrap_or(0);
        Accent::ALL[(idx + 1) % Accent::ALL.len()]
    }

    pub fn color_preview(self, mode: ThemeMode) -> Color {
        self.color(mode)
    }

    fn color(self, mode: ThemeMode) -> Color {
        match self {
            Accent::NyzhiOrange => Color::Rgb(0xEE, 0x60, 0x18),
            Accent::Copper => Color::Rgb(196, 154, 108),
            Accent::Blue => Color::Rgb(59, 130, 246),
            Accent::Orange => Color::Rgb(255, 102, 0),
            Accent::Emerald => Color::Rgb(16, 185, 129),
            Accent::Violet => Color::Rgb(139, 92, 246),
            Accent::Rose => Color::Rgb(244, 63, 94),
            Accent::Amber => Color::Rgb(245, 158, 11),
            Accent::Cyan => Color::Rgb(6, 182, 212),
            Accent::Red => Color::Rgb(239, 68, 68),
            Accent::Pink => Color::Rgb(236, 72, 153),
            Accent::Teal => Color::Rgb(20, 184, 166),
            Accent::Indigo => Color::Rgb(99, 102, 241),
            Accent::Lime => Color::Rgb(132, 204, 22),
            Accent::Monochrome => match mode {
                ThemeMode::Light => Color::Rgb(130, 91, 50),
                ThemeMode::Dark => Color::Rgb(196, 154, 108),
            },
            Accent::Gold => Color::Rgb(255, 215, 0),
            Accent::Coral => Color::Rgb(255, 107, 107),
            Accent::Peach => Color::Rgb(255, 180, 162),
            Accent::Tangerine => Color::Rgb(255, 145, 73),
            Accent::Salmon => Color::Rgb(250, 128, 114),
            Accent::Sunset => Color::Rgb(250, 121, 33),
            Accent::Bronze => Color::Rgb(205, 127, 50),
            Accent::Lavender => Color::Rgb(180, 167, 214),
            Accent::Mint => Color::Rgb(152, 216, 170),
            Accent::Sky => Color::Rgb(135, 206, 235),
            Accent::Frost => Color::Rgb(160, 210, 219),
            Accent::Periwinkle => Color::Rgb(204, 204, 255),
            Accent::Steel => Color::Rgb(70, 130, 180),
            Accent::Lilac => Color::Rgb(200, 162, 200),
            Accent::Ruby => Color::Rgb(224, 17, 95),
            Accent::Sapphire => Color::Rgb(15, 82, 186),
            Accent::Jade => Color::Rgb(0, 168, 107),
            Accent::Crimson => Color::Rgb(220, 20, 60),
            Accent::Magenta => Color::Rgb(255, 0, 255),
            Accent::Plum => Color::Rgb(221, 160, 221),
            Accent::Mauve => Color::Rgb(201, 160, 220),
            Accent::Sage => Color::Rgb(157, 192, 139),
            Accent::Forest => Color::Rgb(34, 139, 34),
            Accent::Olive => Color::Rgb(128, 128, 0),
            Accent::Maroon => Color::Rgb(128, 0, 0),
            Accent::Slate => Color::Rgb(112, 128, 144),
            Accent::Topaz => Color::Rgb(255, 200, 124),
            Accent::Turquoise => Color::Rgb(64, 224, 208),
            Accent::Chartreuse => Color::Rgb(127, 255, 0),
            Accent::Midnight => Color::Rgb(25, 25, 112),
        }
    }

    fn muted(self, mode: ThemeMode) -> Color {
        let base = self.color(mode);
        let (br, bg, bb) = match mode {
            ThemeMode::Dark => (0u8, 0u8, 0u8),
            ThemeMode::Light => (245u8, 240u8, 232u8),
        };
        if let Color::Rgb(r, g, b) = base {
            Color::Rgb(blend(r, br, 38), blend(g, bg, 38), blend(b, bb, 38))
        } else {
            base
        }
    }
}

fn blend(fg: u8, bg: u8, alpha: u8) -> u8 {
    let a = alpha as u16;
    ((fg as u16 * a + bg as u16 * (255 - a)) / 255) as u8
}

fn parse_hex_color(s: &str) -> Option<Color> {
    let s = s.strip_prefix('#').unwrap_or(s);
    if s.len() != 6 {
        return None;
    }
    let r = u8::from_str_radix(&s[0..2], 16).ok()?;
    let g = u8::from_str_radix(&s[2..4], 16).ok()?;
    let b = u8::from_str_radix(&s[4..6], 16).ok()?;
    Some(Color::Rgb(r, g, b))
}

#[derive(Debug, Clone)]
pub struct Theme {
    pub mode: ThemeMode,
    pub preset: ThemePreset,
    pub accent_type: Accent,

    pub bg_page: Color,
    pub bg_surface: Color,
    pub bg_elevated: Color,
    pub bg_sunken: Color,

    pub text_primary: Color,
    pub text_secondary: Color,
    pub text_tertiary: Color,
    pub text_disabled: Color,

    pub border_default: Color,
    pub border_strong: Color,

    pub accent: Color,
    pub accent_muted: Color,

    pub success: Color,
    pub danger: Color,
    pub warning: Color,
    pub info: Color,
}

impl Theme {
    pub fn new(preset: ThemePreset, accent: Accent) -> Self {
        let mut theme = preset.palette();
        theme.accent_type = accent;
        theme.accent = accent.color(theme.mode);
        theme.accent_muted = accent.muted(theme.mode);
        theme
    }

    pub fn from_config(config: &nyzhi_config::TuiConfig) -> Self {
        let preset = ThemePreset::from_name(&config.theme);
        let accent = Accent::from_name(&config.accent);
        let mut theme = Self::new(preset, accent);
        theme.apply_overrides(&config.colors);
        theme
    }

    pub fn apply_overrides(&mut self, overrides: &nyzhi_config::ThemeOverrides) {
        macro_rules! apply {
            ($field:ident) => {
                if let Some(ref hex) = overrides.$field {
                    if let Some(c) = parse_hex_color(hex) {
                        self.$field = c;
                    }
                }
            };
        }
        apply!(bg_page);
        apply!(bg_surface);
        apply!(bg_elevated);
        apply!(bg_sunken);
        apply!(text_primary);
        apply!(text_secondary);
        apply!(text_tertiary);
        apply!(text_disabled);
        apply!(border_default);
        apply!(border_strong);
        apply!(accent);
        apply!(accent_muted);
        apply!(success);
        apply!(danger);
        apply!(warning);
        apply!(info);
    }

    pub fn next_preset(&mut self) {
        let idx = ThemePreset::ALL
            .iter()
            .position(|&p| p == self.preset)
            .unwrap_or(0);
        let next = ThemePreset::ALL[(idx + 1) % ThemePreset::ALL.len()];
        *self = Self::new(next, self.accent_type);
    }

    pub fn next_accent(&mut self) {
        let next = self.accent_type.next();
        *self = Self::new(self.preset, next);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn preset_round_trip() {
        for preset in ThemePreset::ALL {
            let name = preset.name();
            let parsed = ThemePreset::from_name(name);
            assert_eq!(*preset, parsed, "round-trip failed for {name}");
        }
    }

    #[test]
    fn backward_compat_dark_light() {
        assert_eq!(ThemePreset::from_name("dark"), ThemePreset::NyzhiDark);
        assert_eq!(ThemePreset::from_name("light"), ThemePreset::NyzhiLight);
    }

    #[test]
    fn all_presets_produce_valid_theme() {
        for preset in ThemePreset::ALL {
            let theme = Theme::new(*preset, Accent::Blue);
            assert_eq!(theme.preset, *preset);
            assert_eq!(theme.accent_type, Accent::Blue);
        }
    }

    #[test]
    fn parse_hex() {
        assert_eq!(parse_hex_color("#ff0000"), Some(Color::Rgb(255, 0, 0)));
        assert_eq!(parse_hex_color("00ff00"), Some(Color::Rgb(0, 255, 0)));
        assert_eq!(parse_hex_color("#xyz"), None);
        assert_eq!(parse_hex_color(""), None);
    }

    #[test]
    fn overrides_applied() {
        let mut theme = Theme::new(ThemePreset::NyzhiDark, Accent::Copper);
        let overrides = nyzhi_config::ThemeOverrides {
            bg_page: Some("#ff0000".to_string()),
            text_primary: Some("#00ff00".to_string()),
            ..Default::default()
        };
        theme.apply_overrides(&overrides);
        assert_eq!(theme.bg_page, Color::Rgb(255, 0, 0));
        assert_eq!(theme.text_primary, Color::Rgb(0, 255, 0));
    }

    #[test]
    fn accent_round_trip() {
        for accent in Accent::ALL {
            let name = accent.name();
            let parsed = Accent::from_name(name);
            assert_eq!(*accent, parsed, "round-trip failed for accent {name}");
        }
    }
}
